### PR TITLE
added HUB75AB 2-bit row select address

### PR DESCRIPTION
**Pull request by arahasya**

### CODE REVIEW

**Comment by arahasya** [comment]
Working on adding support for RemapZStripe for Outdoor 16x32 panels

WhatsApp Image 2020-06-19 at 14 34 25

I know the logic behind this but it's hard to put it into code. Don't have much coding knowledge. 
Can you help again please?

Resolution 448x64

- DPI width = 928
- DPI height = 61 (4x15 +1)

**Comment by rjrouquette** [comment]
The row encoding part looks good.  I'll let you know when I have the interleaving figured out.

**Comment by rjrouquette** [comment]
I've added the RemapInterleavedZ16AB class.  It works basically the same way as RemapInterleaved32A but the stripes are smaller.

**Comment by arahasya** [comment]
Sorry, I made a mistake. X is interleaved at 8 and not 16. It will be 8-pixel stripe
I changed the x interleave values to these : -

x = (x & 0x7u) | ((x & 0x7ffffff8u) << 1u) | (offset << 2u);

This is the result
WhatsApp Image 2020-06-20 at 12 46 45

**Comment by arahasya** [comment]
Here is the relevant code from rpi-rgb-led-matrix for this particular mapper is this helps.

`class ZStripeMultiplexMapper : public MultiplexMapperBase {
public:
  ZStripeMultiplexMapper(const char *name, int even_vblock_offset, int odd_vblock_offset)
  : MultiplexMapperBase(name, 2),
    even_vblock_offset_(even_vblock_offset),
    odd_vblock_offset_(odd_vblock_offset) {}

  void MapSinglePanel(int x, int y, int *matrix_x, int *matrix_y) const {
    static const int tile_width = 8;
    static const int tile_height = 4;

    const int vert_block_is_odd = ((y / tile_height) % 2);

    const int even_vblock_shift = (1 - vert_block_is_odd) * even_vblock_offset_;
    const int odd_vblock_shitf = vert_block_is_odd * odd_vblock_offset_;

    *matrix_x = x + ((x + even_vblock_shift) / tile_width) * tile_width + odd_vblock_shitf;
    *matrix_y = (y % tile_height) + tile_height * (y / (tile_height * 2));
  }

private:
  const int even_vblock_offset_;
  const int odd_vblock_offset_;
};
`

**Comment by arahasya** [comment]
Here is the relevant code from rpi-rgb-led-matrix lib if this helps


    `class ZStripeMultiplexMapper : public MultiplexMapperBase {
      public:
       ZStripeMultiplexMapper(const char *name, int even_vblock_offset, int odd_vblock_offset)
       : MultiplexMapperBase(name, 2),
         even_vblock_offset_(even_vblock_offset),
         odd_vblock_offset_(odd_vblock_offset) {}

       void MapSinglePanel(int x, int y, int *matrix_x, int *matrix_y) const {
         static const int tile_width = 8;
         static const int tile_height = 4;

         const int vert_block_is_odd = ((y / tile_height) % 2);

         const int even_vblock_shift = (1 - vert_block_is_odd) * even_vblock_offset_;
         const int odd_vblock_shitf = vert_block_is_odd * odd_vblock_offset_;

         *matrix_x = x + ((x + even_vblock_shift) / tile_width) * tile_width + odd_vblock_shitf;
         *matrix_y = (y % tile_height) + tile_height * (y / (tile_height * 2));
       }

     private:
        const int even_vblock_offset_;
       const int odd_vblock_offset_;
     };`

**Comment by rjrouquette** [comment]
I've added RemapInterleavedZ8AB.  You were close, but the left shift for offset need to be changed as well.

**Comment by rjrouquette** [comment]
If you're interested, I took some time to reorganize the code and hopefully make it easier to use.  Specifying the interleaving is now part of the driver construction and the interleaving is now separate from the the PixelMapping class.  I also changed how the driver handles the dimensions at each translation level.  As a result, the getWidth() and getHeight() functions now return the actual raster dimensions for drawing instead the raw chain dimensions.  There is now also getCanvasWidth() and getCanvasHeight() for if you do specify a separate custom mapping such as rotation, mirroring, or changing the chain layout.

I hope this makes things easier.

**Comment by arahasya** [comment]
Yes! Definitely makes things easier. Thanks again!

**Pull request merged**
